# Generated by Django 3.0.5 on 2020-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_word', models.CharField(max_length=50)),
                ('meaning', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
    ]
