# Generated by Django 3.0.5 on 2020-04-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='videolink',
        ),
    ]
