# Generated by Django 3.0.5 on 2020-04-30 18:42

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200430_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videolink',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
