# Generated by Django 3.0.5 on 2020-04-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200430_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
